### PR TITLE
Add mod marketing files

### PR DESCRIPTION
**Pull request by grad-ler**
adjusted base.toml
adjusted mod.cpp
added new logo files

### CODE REVIEW

**Comment by grad-ler** [comment]
github_social_preview and steam_logo are yet to be updated
steam_logo
github_social_preview

pseudo_custom_adler
pseudo_custom_adler

Edit: Added the correct files.

**Comment by y0014984** [comment]
I've updated the social preview.

**Comment by y0014984** [comment]
Currently there is no Steam Workshop Version but I will update the GitHub release to include the marketing changes.

**Comment by grad-ler** [comment]
> github_social_preview and steam_logo are yet to be updated steam_logo github_social_preview
> 
> pseudo_custom_adler pseudo_custom_adler
> 
> Edit: Added the correct files.

I corrected the images in this comment, they were the wrong ones.

**Comment by y0014984** [comment]
> I corrected the images in this comment, they were the wrong ones.

I know. I've checked that before merging.

**Pull request merged**
